-- 002_SeedRadicals.sql
-- Seed the Kangxi Chinese Radicals

DO $$
BEGIN
IF NOT EXISTS (SELECT 1 FROM "Radicals") THEN
    INSERT INTO "Radicals" ("Id", "Character", "StrokeCount", "VietnameseMeaning", "Pinyin", "Reading", "CreatedDate", "CreatedBy", "IsDeleted") VALUES
    -- 1 Stroke
    (gen_random_uuid(), '一', 1, 'Nhất (một)', 'yī', 'ichi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '丨', 1, 'Cổn (sổ thẳng)', 'gǔn', 'tate', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '丶', 1, 'Chủ (chấm)', 'zhǔ', 'ten', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '丿', 1, 'Phiệt (phẩy)', 'piě', 'no', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '乙', 1, 'Ất (vẹo, cong)', 'yǐ', 'otsu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '亅', 1, 'Quyết (móc)', 'jué', 'hane', CURRENT_TIMESTAMP, 'System', FALSE),
    
    -- 2 Strokes
    (gen_random_uuid(), '二', 2, 'Nhị (hai)', 'èr', 'ni', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '亠', 2, 'Đầu (chữ đầu)', 'tóu', 'nabe-buta', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '人', 2, 'Nhân (người)', 'rén', 'hito', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '儿', 2, 'Nhân đi (ngõa)', 'ér', 'ninyō', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '入', 2, 'Nhập (vào)', 'rù', 'iru', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '八', 2, 'Bát (tám)', 'bā', 'hachi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '冂', 2, 'Quynh (vây quanh)', 'jiōng', 'maki-gama', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '冖', 2, 'Mịch (trùm lên)', 'mì', 'wakanmuri', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '冫', 2, 'Băng (nước đá)', 'bīng', 'nisui', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '几', 2, 'Kỷ (ghế tựa)', 'jī', 'tsukue', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '凵', 2, 'Khảm (há miệng)', 'qiǎn', 'uke-bako', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '刀', 2, 'Đao (con dao)', 'dāo', 'katana', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '力', 2, 'Lực (sức mạnh)', 'lì', 'chikara', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '勹', 2, 'Bao (bọc, gói)', 'bāo', 'tsutumi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '匕', 2, 'Chủy (cái thìa)', 'bǐ', 'saji', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '匚', 2, 'Phương (tủ đựng)', 'fāng', 'hako-gama', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '匸', 2, 'Hệ (che đậy)', 'xì', 'kakushi-gama', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '十', 2, 'Thập (mười)', 'shí', 'jū', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '卜', 2, 'Bốc (xem bói)', 'bǔ', 'to', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '卩', 2, 'Tiết (tre, đốt tre)', 'jié', 'fushi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '厂', 2, 'Hán (sườn núi)', 'chǎng', 'gandare', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '厶', 2, 'Khư (riêng tư)', 'sī', 'mu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '又', 2, 'Hựu (lại nữa)', 'yòu', 'mata', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 3 Strokes
    (gen_random_uuid(), '口', 3, 'Khẩu (miệng)', 'kǒu', 'kuchi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '囗', 3, 'Vi (vây quanh)', 'wéi', 'kuni-gama', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '土', 3, 'Thổ (đất)', 'tǔ', 'tsuchi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '士', 3, 'Sĩ (kẻ sĩ)', 'shì', 'samurai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '夂', 3, 'Truy (đi chậm)', 'zhǐ', 'fuyu-gashira', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '夊', 3, 'Tuy (đi chậm)', 'suī', 'sui', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '夕', 3, 'Tịch (đêm tối)', 'xī', 'yūbe', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '大', 3, 'Đại (to lớn)', 'dà', 'ō', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '女', 3, 'Nữ (phụ nữ)', 'nǚ', 'onna', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '子', 3, 'Tử (con)', 'zǐ', 'ko', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '宀', 3, 'Miên (mái nhà)', 'mián', 'u-kanmuri', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '寸', 3, 'Thốn (tấc)', 'cùn', 'sun', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '小', 3, 'Tiểu (nhỏ bé)', 'xiǎo', 'chīsai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '尢', 3, 'Uông (yếu ớt)', 'yóu', 'daino-muni', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '尸', 3, 'Thi (xác chết)', 'shī', 'shikabane', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '屮', 3, 'Triệt (mầm non)', 'chè', 'tetsu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '山', 3, 'Sơn (núi)', 'shān', 'yama', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '巛', 3, 'Xuyên (sông ngòi)', 'chuān', 'maga-gawa', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '工', 3, 'Công (thợ, công việc)', 'gōng', 'takumi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '己', 3, 'Kỷ (bản thân)', 'jǐ', 'onore', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '巾', 3, 'Cân (khăn)', 'jīn', 'haba', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '干', 3, 'Can (thiên can)', 'gān', 'hanni', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '幺', 3, 'Yêu (nhỏ nhắn)', 'yāo', 'ito-gashira', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '广', 3, 'Quảng (mái nhà rộng)', 'guǎng', 'madare', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '廴', 3, 'Dẫn (bước dài)', 'yǐn', 'ennyō', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '廾', 3, 'Củng (chắp tay)', 'gǒng', 'niju-ashi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '弋', 3, 'Dực (bắn cung)', 'yì', 'ishiki', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '弓', 3, 'Cung (cái cung)', 'gōng', 'yumi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '彐', 3, 'Ký (đầu heo)', 'jì', 'keigashira', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '彡', 3, 'Sâm (lông tóc)', 'shān', 'sanzukuri', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '彳', 3, 'Xích (bước chân trái)', 'chì', 'gyōnin-ben', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 4 Strokes
    (gen_random_uuid(), '心', 4, 'Tâm (quả tim)', 'xīn', 'kokoro', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '戈', 4, 'Qua (cái mác)', 'gē', 'hoko', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '戶', 4, 'Hộ (cánh cửa)', 'hù', 'to', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '手', 4, 'Thủ (tay)', 'shǒu', 'te', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '支', 4, 'Chi (cành cây)', 'zhī', 'shin-nyō', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '攴', 4, 'Phộc (đánh nhẹ)', 'pū', 'bokuzukuri', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '文', 4, 'Văn (văn chương)', 'wén', 'bun', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '斗', 4, 'Đấu (cái đấu)', 'dǒu', 'to', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '斤', 4, 'Cân (cái rìu)', 'jīn', 'ono', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '方', 4, 'Phương (hướng, vuông)', 'fāng', 'kata', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '无', 4, 'Vô (không có)', 'wú', 'nashi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '日', 4, 'Nhật (mặt trời)', 'rì', 'hi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '曰', 4, 'Viết (nói rằng)', 'yuē', 'hirabi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '月', 4, 'Nguyệt (mặt trăng)', 'yuè', 'tsuki', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '木', 4, 'Mộc (cây)', 'mù', 'ki', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '欠', 4, 'Khiếm (thiếu thốn)', 'qiàn', 'akabi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '止', 4, 'Chỉ (dừng lại)', 'zhǐ', 'tome', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '歹', 4, 'Đãi (xương tàn)', 'dǎi', 'gatsu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '殳', 4, 'Thù (cái gậy)', 'shū', 'hoko', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '毋', 4, 'Vô (chớ, đừng)', 'wú', 'nakare', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '比', 4, 'Tỉ (so sánh)', 'bǐ', 'kurabe', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '毛', 4, 'Mao (lông)', 'máo', 'ke', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '氏', 4, 'Thị (họ)', 'shì', 'uji', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '气', 4, 'Khí (hơi nước)', 'qì', 'kigama', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '水', 4, 'Thủy (nước)', 'shuǐ', 'mizu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '火', 4, 'Hỏa (lửa)', 'huǒ', 'hi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '爪', 4, 'Trảo (móng vuốt)', 'zhǎo', 'tsume', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '父', 4, 'Phụ (cha)', 'fù', 'chichi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '爻', 4, 'Hào (hào âm dương)', 'yáo', 'kō', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '爿', 4, 'Tường (mảnh gỗ)', 'qiáng', 'shō-hen', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '片', 4, 'Phiến (mảnh lá)', 'piàn', 'kata', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '牙', 4, 'Nha (răng)', 'yá', 'kiba', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '牛', 4, 'Ngưu (trâu, bò)', 'niú', 'ushi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '犬', 4, 'Khuyển (chó)', 'quǎn', 'inu', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 5 Strokes
    (gen_random_uuid(), '玄', 5, 'Huyền (màu đen)', 'xuán', 'gen', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '玉', 5, 'Ngọc (đá quý)', 'yù', 'tama', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '瓜', 5, 'Qua (quả dưa)', 'guā', 'uri', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '瓦', 5, 'Ngõa (ngói đất nung)', 'wǎ', 'kawara', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '甘', 5, 'Cam (ngọt ngào)', 'gān', 'amai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '生', 5, 'Sinh (sinh sống)', 'shēng', 'umareru', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '用', 5, 'Dụng (sử dụng)', 'yòng', 'mochiiru', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '田', 5, 'Điền (ruộng)', 'tián', 'ta', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '疋', 5, 'Sơ (cuộn vải)', 'pǐ', 'hiki', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '疒', 5, 'Nạch (bệnh tật)', 'nè', 'yamai-dare', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '癶', 5, 'Bát (đạp chân)', 'bō', 'hatsugashira', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '白', 5, 'Bạch (màu trắng)', 'bái', 'shiro', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '皮', 5, 'Bì (da thú)', 'pí', 'kega-wa', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '皿', 5, 'Mãnh (bát đĩa)', 'mǐn', 'sara', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '目', 5, 'Mục (mắt)', 'mù', 'me', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '矛', 5, 'Mâu (cây thương)', 'máo', 'hoko', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '矢', 5, 'Thỉ (mũi tên)', 'shǐ', 'ya', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '石', 5, 'Thạch (đá)', 'shí', 'ishi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '示', 5, 'Thị (cúng tế)', 'shì', 'shimesu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '禸', 5, 'Nhựu (vết chân thú)', 'róu', 'jū', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '禾', 5, 'Hòa (lúa mì)', 'hé', 'nogi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '穴', 5, 'Huyệt (hang lỗ)', 'xué', 'ana', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '立', 5, 'Lập (đứng thẳng)', 'lì', 'tatsu', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 6 Strokes
    (gen_random_uuid(), '竹', 6, 'Trúc (tre trúc)', 'zhú', 'take', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '米', 6, 'Mễ (gạo)', 'mǐ', 'kome', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '糸', 6, 'Mịch (sợi tơ)', 'mì', 'ito', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '缶', 6, 'Phẫu (đồ sành sứ)', 'fǒu', 'kame', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '网', 6, 'Võng (tấm lưới)', 'wǎng', 'ami', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '羊', 6, 'Dương (con dê)', 'yáng', 'hitsuji', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '羽', 6, 'Vũ (lông vũ)', 'yǔ', 'hane', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '老', 6, 'Lão (người già)', 'lǎo', 'oi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '化', 6, 'Hóa (biến hóa)', 'huà', 'ka', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '耒', 6, 'Lỗi (cái cày)', 'lěi', 'suki', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '耳', 6, 'Nhĩ (tai)', 'ěr', 'mimi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '聿', 6, 'Duật (cây bút)', 'yù', 'fude', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '肉', 6, 'Nhục (thịt)', 'ròu', 'niku', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '臣', 6, 'Thần (bầy tôi)', 'chén', 'shin', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '自', 6, 'Tự (bản thân)', 'zì', 'mizukara', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '至', 6, 'Chí (đến nơi)', 'zhì', 'itaru', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '臼', 6, 'Cối (cái cối)', 'jiù', 'usu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '舌', 6, 'Thiệt (cái lưỡi)', 'shé', 'shita', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '舛', 6, 'Suyễn (sai lệch)', 'chuǎn', 'somuku', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '舟', 6, 'Chu (con thuyền)', 'zhōu', 'fune', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '艮', 6, 'Cấn (bền cứng)', 'gèn', 'ushitora', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '色', 6, 'Sắc (màu sắc)', 'sè', 'iro', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '艸', 6, 'Thảo (cỏ)', 'cǎo', 'kusa', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '虍', 6, 'Hô (vằn cọp)', 'hū', 'tora-ganmuri', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '虫', 6, 'Trùng (sâu bọ)', 'chóng', 'mushi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '血', 6, 'Huyết (máu)', 'xuè', 'chi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '行', 6, 'Hành (đi đường)', 'xíng', 'gyō', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '衣', 6, 'Y (áo quần)', 'yī', 'koromo', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '襾', 6, 'Á (che đậy)', 'yà', 'nishi', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 7 Strokes
    (gen_random_uuid(), '見', 7, 'Kiến (nhìn)', 'jiàn', 'miru', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '角', 7, 'Giác (sừng)', 'jiǎo', 'tsuno', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '言', 7, 'Ngôn (nói)', 'yán', 'kotoba', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '谷', 7, 'Cốc (khe nước)', 'gǔ', 'tani', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '豆', 7, 'Đậu (hạt đậu)', 'dòu', 'mame', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '豕', 7, 'Thỉ (con heo)', 'shǐ', 'buta', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '豸', 7, 'Trĩ (loài sâu bò)', 'zhì', 'mujina', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '貝', 7, 'Bối (vỏ sò, của cải)', 'bèi', 'kai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '赤', 7, 'Xích (màu đỏ)', 'chì', 'aka', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '走', 7, 'Tẩu (chạy)', 'zǒu', 'hashiru', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '足', 7, 'Túc (chân)', 'zú', 'ashi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '身', 7, 'Thân (thân thể)', 'shēn', 'mi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '車', 7, 'Xa (chiếc xe)', 'chē', 'kuruma', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '辛', 7, 'Tân (cay đắng)', 'xīn', 'karai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '辰', 7, 'Thần (giờ thìn)', 'chén', 'shin-no-tatsu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '辵', 7, 'Sước (chợt đi chợt dừng)', 'chuò', 'shin-nyū', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '邑', 7, 'Ấp (đất đai)', 'yì', 'ōzatocan', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '酉', 7, 'Dậu (vò rượu)', 'yǒu', 'tori', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '采', 7, 'Biện (phân biệt)', 'cǎi', 'nogome', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '里', 7, 'Lý (dặm đường, làng)', 'lǐ', 'sato', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 8 Strokes
    (gen_random_uuid(), '金', 8, 'Kim (vàng, kim loại)', 'jīn', 'kane', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '長', 8, 'Trường (dài)', 'cháng', 'nagai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '門', 8, 'Môn (cửa hai cánh)', 'mén', 'kado', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '阜', 8, 'Phụ (gò đất)', 'fù', 'kozato-ben', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '隶', 8, 'Lệ (bắt giữ)', 'lì', 'otobu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '隹', 8, 'Chuy (chim đuôi ngắn)', 'zhuī', 'furutori', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '雨', 8, 'Vũ (mưa)', 'yǔ', 'ame', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '靑', 8, 'Thanh (màu xanh)', 'qīng', 'ao', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '非', 8, 'Phi (sai lầm)', 'fēi', 'arazu', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 9 Strokes
    (gen_random_uuid(), '面', 9, 'Diện (khuôn mặt)', 'miàn', 'men', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '革', 9, 'Cách (da thú thay đổi)', 'gé', 'kawa', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '韋', 9, 'Vi (da thuộc)', 'wéi', 'kameshiki', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '韭', 9, 'Cửu (cây hẹ)', 'jiǔ', 'nira', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '音', 9, 'Âm (âm thanh)', 'yīn', 'oto', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '頁', 9, 'Hiệt (trang giấy)', 'yè', 'ōgai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '風', 9, 'Phong (gió)', 'fēng', 'kaze', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '飛', 9, 'Phi (bay)', 'fēi', 'tobu', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '食', 9, 'Thực (ăn)', 'shí', 'shoku', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '首', 9, 'Thủ (đầu)', 'shǒu', 'kubi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '香', 9, 'Hương (mùi thơm)', 'xiāng', 'kaori', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 10 Strokes
    (gen_random_uuid(), '馬', 10, 'Mã (con ngựa)', 'mǎ', 'uma', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '骨', 10, 'Cốt (xương)', 'gǔ', 'hone', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '高', 10, 'Cao (cao lớn)', 'gāo', 'takai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '髟', 10, 'Bưu (tóc dài)', 'biāo', 'kami-gashira', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鬥', 10, 'Đấu (đánh nhau)', 'dòu', 'tatakai', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鬯', 10, 'Sưởng (rượu tế)', 'chàng', 'chō', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鬲', 10, 'Lịch (cái nồi cổ)', 'lì', 'kanae', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鬼', 10, 'Quỷ (con quỷ)', 'guǐ', 'oni', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 11 Strokes
    (gen_random_uuid(), '魚', 11, 'Ngư (con cá)', 'yú', 'sakana', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鳥', 11, 'Điểu (con chim)', 'niǎo', 'tori', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鹵', 11, 'Lỗ (đất mặn)', 'lǔ', 'shio', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鹿', 11, 'Lộc (con hươu)', 'lù', 'shika', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '麥', 11, 'Mạch (lúa mạch)', 'mài', 'mugi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '麻', 11, 'Ma (cây gai)', 'má', 'asa', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 12 Strokes
    (gen_random_uuid(), '黃', 12, 'Hoàng (màu vàng)', 'huáng', 'kiiro', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '黍', 12, 'Thử (cây nếp)', 'shǔ', 'kibi', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '黑', 12, 'Hắc (màu đen)', 'hēi', 'kuro', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '黹', 12, 'Chỉ (may vá)', 'zhǐ', 'nuihazi', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 13 Strokes
    (gen_random_uuid(), '黽', 13, 'Mãnh (con ếch)', 'mǐn', 'aogamaru', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鼎', 13, 'Đỉnh (cái vạc tế)', 'dǐng', 'kanae', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鼓', 13, 'Cổ (cái trống)', 'gǔ', 'taiko', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '鼠', 13, 'Thử (con chuột)', 'shǔ', 'nezumi', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 14 Strokes
    (gen_random_uuid(), '鼻', 14, 'Tị (cái mũi)', 'bí', 'hana', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '齊', 14, 'Tề (ngay ngắn)', 'qí', 'hitoshi', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 15 Strokes
    (gen_random_uuid(), '齒', 15, 'Xỉ (răng)', 'chǐ', 'ha', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 16 Strokes
    (gen_random_uuid(), '龍', 16, 'Long (con rồng)', 'lóng', 'ryū', CURRENT_TIMESTAMP, 'System', FALSE),
    (gen_random_uuid(), '龜', 16, 'Quy (con rùa)', 'guī', 'kame', CURRENT_TIMESTAMP, 'System', FALSE),

    -- 17 Strokes
    (gen_random_uuid(), '龠', 17, 'Dược (sáo trúc cổ)', 'yuè', 'fue', CURRENT_TIMESTAMP, 'System', FALSE);
END IF;
END $$;
