-- 001_CreateTables.sql
-- DDL for YK Language Learn Database

CREATE TABLE "Users" (
    "Id" UUID PRIMARY KEY,
    "UserName" VARCHAR(256) NULL,
    "NormalizedUserName" VARCHAR(256) NULL,
    "Email" VARCHAR(256) NULL,
    "NormalizedEmail" VARCHAR(256) NULL,
    "EmailConfirmed" BOOLEAN NOT NULL,
    "PasswordHash" TEXT NULL,
    "SecurityStamp" TEXT NULL,
    "ConcurrencyStamp" TEXT NULL,
    "PhoneNumber" TEXT NULL,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "TwoFactorEnabled" BOOLEAN NOT NULL,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE NULL,
    "LockoutEnabled" BOOLEAN NOT NULL,
    "AccessFailedCount" INTEGER NOT NULL,
    "DisplayName" VARCHAR(150) NOT NULL,
    "AvatarUrl" VARCHAR(500) NULL,
    "ActiveLanguageId" UUID NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

CREATE TABLE "Roles" (
    "Id" UUID PRIMARY KEY,
    "Name" VARCHAR(256) NULL,
    "NormalizedName" VARCHAR(256) NULL,
    "ConcurrencyStamp" TEXT NULL
);

CREATE TABLE "UserClaims" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "ClaimType" TEXT NULL,
    "ClaimValue" TEXT NULL
);

CREATE TABLE "RoleClaims" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" UUID NOT NULL REFERENCES "Roles"("Id") ON DELETE CASCADE,
    "ClaimType" TEXT NULL,
    "ClaimValue" TEXT NULL
);

CREATE TABLE "UserLogins" (
    "LoginProvider" VARCHAR(128) NOT NULL,
    "ProviderKey" VARCHAR(128) NOT NULL,
    "ProviderDisplayName" TEXT NULL,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE "UserRoles" (
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "RoleId" UUID NOT NULL REFERENCES "Roles"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE "UserTokens" (
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Value" TEXT NULL,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE INDEX "IX_Users_NormalizedEmail" ON "Users" ("NormalizedEmail");
CREATE INDEX "IX_Users_NormalizedUserName" ON "Users" ("NormalizedUserName");
CREATE INDEX "IX_Roles_NormalizedName" ON "Roles" ("NormalizedName");

-- Languages Table
CREATE TABLE "Languages" (
    "Id" UUID PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "LocaleCode" VARCHAR(10) NOT NULL,
    "IsDefault" BOOLEAN NOT NULL,
    "UserId" UUID NULL REFERENCES "Users"("Id") ON DELETE SET NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- Add foreign key constraint for ActiveLanguageId in Users (circular relationship resolved by creating Languages first or adding FK now)
ALTER TABLE "Users" 
    ADD CONSTRAINT "FK_Users_Languages_ActiveLanguageId" 
    FOREIGN KEY ("ActiveLanguageId") REFERENCES "Languages"("Id") ON DELETE RESTRICT;

-- UserLanguages Table
CREATE TABLE "UserLanguages" (
    "Id" UUID PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);
CREATE UNIQUE INDEX "IX_UserLanguages_UserId_LanguageId" ON "UserLanguages" ("UserId", "LanguageId");

-- Categories Table
CREATE TABLE "Categories" (
    "Id" UUID PRIMARY KEY,
    "Name" VARCHAR(150) NOT NULL,
    "Description" VARCHAR(500) NULL,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- Words Table
CREATE TABLE "Words" (
    "Id" UUID PRIMARY KEY,
    "Text" VARCHAR(200) NOT NULL,
    "IPA" VARCHAR(150) NULL,
    "AudioUrl" VARCHAR(500) NULL,
    "ImageUrl" VARCHAR(500) NULL,
    "Note" VARCHAR(1000) NULL,
    "Status" VARCHAR(50) NOT NULL,
    "CategoryId" UUID NOT NULL REFERENCES "Categories"("Id") ON DELETE CASCADE,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- WordMeanings Table
CREATE TABLE "WordMeanings" (
    "Id" UUID PRIMARY KEY,
    "WordId" UUID NOT NULL REFERENCES "Words"("Id") ON DELETE CASCADE,
    "TypeOfWord" VARCHAR(50) NOT NULL,
    "MeaningText" VARCHAR(1000) NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- WordExamples Table
CREATE TABLE "WordExamples" (
    "Id" UUID PRIMARY KEY,
    "WordId" UUID NOT NULL REFERENCES "Words"("Id") ON DELETE CASCADE,
    "Sentence" VARCHAR(1000) NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- ReviewLists Table
CREATE TABLE "ReviewLists" (
    "Id" UUID PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);
CREATE UNIQUE INDEX "IX_ReviewLists_UserId_LanguageId" ON "ReviewLists" ("UserId", "LanguageId");

-- ReviewListWords Table
CREATE TABLE "ReviewListWords" (
    "Id" UUID PRIMARY KEY,
    "ReviewListId" UUID NOT NULL REFERENCES "ReviewLists"("Id") ON DELETE CASCADE,
    "WordId" UUID NOT NULL REFERENCES "Words"("Id") ON DELETE CASCADE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);
CREATE UNIQUE INDEX "IX_ReviewListWords_ReviewListId_WordId" ON "ReviewListWords" ("ReviewListId", "WordId");

-- GrammarRules Table
CREATE TABLE "GrammarRules" (
    "Id" UUID PRIMARY KEY,
    "Name" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(4000) NOT NULL,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- GrammarExamples Table
CREATE TABLE "GrammarExamples" (
    "Id" UUID PRIMARY KEY,
    "GrammarRuleId" UUID NOT NULL REFERENCES "GrammarRules"("Id") ON DELETE CASCADE,
    "Sentence" VARCHAR(1000) NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- SentenceStructures Table
CREATE TABLE "SentenceStructures" (
    "Id" UUID PRIMARY KEY,
    "Pattern" VARCHAR(300) NOT NULL,
    "VietnameseMeaning" VARCHAR(1000) NOT NULL,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- SentenceStructureExamples Table
CREATE TABLE "SentenceStructureExamples" (
    "Id" UUID PRIMARY KEY,
    "SentenceStructureId" UUID NOT NULL REFERENCES "SentenceStructures"("Id") ON DELETE CASCADE,
    "Sentence" VARCHAR(1000) NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- StudySessions Table
CREATE TABLE "StudySessions" (
    "Id" UUID PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "StartTime" TIMESTAMP WITH TIME ZONE NOT NULL,
    "EndTime" TIMESTAMP WITH TIME ZONE NULL,
    "Mode" VARCHAR(50) NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- TestResults Table
CREATE TABLE "TestResults" (
    "Id" UUID PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "LanguageId" UUID NOT NULL REFERENCES "Languages"("Id") ON DELETE CASCADE,
    "TestType" VARCHAR(50) NOT NULL,
    "Score" INTEGER NOT NULL,
    "TotalQuestions" INTEGER NOT NULL,
    "Duration" INTEGER NOT NULL,
    "ConfigSnapshot" VARCHAR(2000) NULL,
    "TakenAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- Radicals Table
CREATE TABLE "Radicals" (
    "Id" UUID PRIMARY KEY,
    "Character" VARCHAR(20) NOT NULL,
    "StrokeCount" INTEGER NOT NULL,
    "VietnameseMeaning" VARCHAR(200) NOT NULL,
    "Pinyin" VARCHAR(100) NULL,
    "Reading" VARCHAR(200) NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- RadicalExamples Table
CREATE TABLE "RadicalExamples" (
    "Id" UUID PRIMARY KEY,
    "RadicalId" UUID NOT NULL REFERENCES "Radicals"("Id") ON DELETE CASCADE,
    "Word" VARCHAR(200) NOT NULL,
    "VietnameseMeaning" VARCHAR(500) NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);

-- RefreshTokens Table
CREATE TABLE "RefreshTokens" (
    "Id" UUID PRIMARY KEY,
    "UserId" UUID NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Token" VARCHAR(500) NOT NULL,
    "ExpiresAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "IsRevoked" BOOLEAN NOT NULL,
    "CreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CreatedBy" VARCHAR(100) NOT NULL,
    "ModifiedDate" TIMESTAMP WITH TIME ZONE NULL,
    "ModifiedBy" VARCHAR(100) NULL,
    "IsDeleted" BOOLEAN NOT NULL
);
CREATE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");
